const ActionTypes = {
  LOAD_COMMENTS: "LOAD_COMMENTS",
  ADD_COMMENT: "ADD_COMMENT",

  ADD_FEEDBACK: "ADD_FEEDBACK",

  LOAD_DISHES: "LOAD_DISHES",

  LOAD_PROMOS: "LOAD_PROMOS",

  LOAD_LEADERS: "LOAD_LEADERS",
};

export default ActionTypes;
